[package]
name = "kabanos_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
kabanos_common = { path = "../kabanos_common"}
serde_json = "1.0.133"
thiserror = "2.0.3"
tokio = { version = "1.42.0", features = ["full"]}
tower-lsp = "0.20.0"
